# Gradleに割り当てるメモリを増やす
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties
# https://fabricmc.net/develop/ の最新バージョンと合わない場合はここを更新してください
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod properties
mod_version=0.1.0
maven_group=io.github.rnkg2008623
archives_base_name=mc-custom-client

# Dependencies
fabric_version=0.102.0+1.21.1
